nome=input('Digite seu nome: ')
idade=input('Digite sua idade: ')
genero=input('Digite seu Genero: ')
endereco=input('Digite seu endereço: ') 
print(f'Nome: {nome} \nIdade: {idade} \nGenero: {genero} \nEndereço: {endereco}')